Make tests return error on failure, add runall script
Signed-off-by: Olaf Kirch <okir@suse.com>

diff --git a/tests/001-sha256sum b/tests/001-sha256sum
--- a/tests/001-sha256sum
+++ b/tests/001-sha256sum
@@ -37,7 +37,8 @@ found=$TMPDIR/found
 done
 
 if [ -e $found ]; then
-	echo "Good, it seems we detected coverage of a sha256 symbol"
+	echo "PASS: it seems we detected coverage of a sha256 symbol"
 else
-	echo "Did not detect coverage of a sha256 symbol - maybe debuginfo pkg is missing?"
+	echo "FAIL: Did not detect coverage of a sha256 symbol - maybe debuginfo pkg is missing?"
+	exit 1
 fi
diff --git a/tests/002-sleep b/tests/002-sleep
--- a/tests/002-sleep
+++ b/tests/002-sleep
@@ -25,6 +25,6 @@ echo "*** report"
 echo
 
 case $slept in
-1*)	echo "Good, it seems we did not interrupt the sleep() system call";;
-*)	echo "Ouch, it seems sampling interferes with the sleep() system call";;
+1*)	echo "PASS: it seems we did not interrupt the sleep() system call";;
+*)	echo "FAIL: ouch, it seems sampling interferes with the sleep() system call"; exit 1;;
 esac
diff --git a/tests/003-threads b/tests/003-threads
--- a/tests/003-threads
+++ b/tests/003-threads
@@ -37,7 +37,8 @@ found=$TMPDIR/found
 done
 
 if [ -e $TMPDIR/function1 -a -e $TMPDIR/function2 ]; then
-	echo "Good, it seems we detected coverage of both threads"
+	echo "PASS: it seems we detected coverage of both threads"
 else
-	echo "Did not detect coverage of thread functions"
+	echo "FAIL: Did not detect coverage of thread functions"
+	exit 1
 fi
diff --git a/tests/004-dlopen b/tests/004-dlopen
--- a/tests/004-dlopen
+++ b/tests/004-dlopen
@@ -37,7 +37,8 @@ found=$TMPDIR/found
 done
 
 if [ -e $found ]; then
-	echo "Good, it seems we detected coverage of both threads"
+	echo "PASS: it seems we detected coverage of both threads"
 else
-	echo "Did not detect coverage of sqrt"
+	echo "FAIL: Did not detect coverage of sqrt"
+	exit 1
 fi
diff --git a/tests/005-mcount b/tests/005-mcount
--- a/tests/005-mcount
+++ b/tests/005-mcount
@@ -36,8 +36,9 @@ found=$TMPDIR/found
 done
 
 if [ -e $found ]; then
-	echo "Good, it seems we detected coverage elapsed()"
+	echo "PASS: it seems we detected coverage elapsed()"
 else
-	echo "Did not detect coverage of elapsed()"
+	echo "FAIL: Did not detect coverage of elapsed()"
+	exit 1
 fi
 
diff --git a/tests/006-ptrace b/tests/006-ptrace
--- a/tests/006-ptrace
+++ b/tests/006-ptrace
@@ -42,7 +42,8 @@ echo 0 > $found
 
 count=$(cat $found)
 if [ $count -gt 5 ]; then
-	echo "Good, it seems we detected coverage of $count lines"
+	echo "PASS: it seems we detected coverage of $count lines"
 else
-	echo "Did not detect sufficient coverage"
+	echo "FAIL: Did not detect sufficient coverage"
+	exit 1
 fi
